//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.ArticleComments = new HashSet<ArticleComment>();
            this.Buyers = new HashSet<Entity>();
            this.ArticleVotes = new HashSet<ArticleVote>();
        }
    
        public int ID { get; set; }
        public int NewspaperID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string PayOnlyContent { get; set; }
        public string ImgURL { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int VoteScore { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int CreationDay { get; set; }
        public string ShortDescription { get; set; }
        public bool Published { get; set; }
        public decimal GeneratedIncome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleComment> ArticleComments { get; set; }
        public virtual Entity Author { get; set; }
        public virtual Newspaper Newspaper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity> Buyers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleVote> ArticleVotes { get; set; }
    }
}
