//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattleParticipant
    {
        public int ID { get; set; }
        public int CitizenID { get; set; }
        public int BattleID { get; set; }
        public decimal DamageDealt { get; set; }
        public int WeaponQualityUsed { get; set; }
        public bool IsAttacker { get; set; }
        public int Day { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Battle Battle { get; set; }
        public virtual Citizen Citizen { get; set; }
    }
}
