//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Battle()
        {
            this.BattleParticipants = new HashSet<BattleParticipant>();
            this.BattleEvents = new HashSet<BattleEvent>();
        }
    
        public int ID { get; set; }
        public int WarID { get; set; }
        public int RegionID { get; set; }
        public decimal WallHealth { get; set; }
        public bool Active { get; set; }
        public int StartDay { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<bool> WonByAttacker { get; set; }
        public bool AttackerInitiatedBattle { get; set; }
        public decimal DestroyedDevelopment { get; set; }
        public Nullable<decimal> GoldTaken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BattleParticipant> BattleParticipants { get; set; }
        public virtual Region Region { get; set; }
        public virtual War War { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BattleEvent> BattleEvents { get; set; }
    }
}
