//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BugReport
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<int> CitizenID { get; set; }
    
        public virtual Citizen Citizen { get; set; }
    }
}
