//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citizen()
        {
            this.Sessions = new HashSet<Session>();
            this.ContractJobOffers = new HashSet<ContractJobOffer>();
            this.JobContracts = new HashSet<JobContract>();
            this.CongressVotings = new HashSet<CongressVoting>();
            this.PartyPresidentVotes = new HashSet<PartyPresidentVote>();
            this.Parties = new HashSet<Party>();
            this.PartyJoinRequests = new HashSet<PartyJoinRequest>();
            this.PartyPresidentCandidates = new HashSet<PartyPresidentCandidate>();
            this.CongressVotingComments = new HashSet<CongressVotingComment>();
            this.CongressCandidateVotes = new HashSet<CongressCandidateVote>();
            this.CongressCandidates = new HashSet<CongressCandidate>();
            this.CountriesPresident = new HashSet<Country>();
            this.PresidentCandidates = new HashSet<PresidentCandidate>();
            this.PresidentVotes = new HashSet<PresidentVote>();
            this.Organisations = new HashSet<Organisation>();
            this.BattleParticipants = new HashSet<BattleParticipant>();
            this.NewspaperJournalists = new HashSet<NewspaperJournalist>();
            this.BugReports = new HashSet<BugReport>();
            this.Friends = new HashSet<Friend>();
            this.Friends1 = new HashSet<Friend>();
            this.FriendRequests = new HashSet<FriendRequest>();
            this.FriendRequests1 = new HashSet<FriendRequest>();
            this.PartyInvites = new HashSet<PartyInvite>();
            this.Wars = new HashSet<War>();
            this.DevIssueComments = new HashSet<DevIssueComment>();
            this.DevIssues = new HashSet<DevIssue>();
            this.DevIssueVotes = new HashSet<DevIssueVote>();
            this.Uploads = new HashSet<Upload>();
            this.CongressVotes = new HashSet<CongressVote>();
            this.Congressmen = new HashSet<Congressman>();
            this.HotelRooms = new HashSet<HotelRoom>();
            this.HotelManagers = new HashSet<HotelManager>();
            this.Houses = new HashSet<House>();
            this.PartyMemberEvents = new HashSet<PartyMemberEvent>();
        }
    
        public int ID { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool Verified { get; set; }
        public int RegionID { get; set; }
        public int CitizenshipID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int BirthDay { get; set; }
        public int Experience { get; set; }
        public int HitPoints { get; set; }
        public decimal Strength { get; set; }
        public decimal MilitaryRank { get; set; }
        public decimal Manufacturing { get; set; }
        public decimal Raw { get; set; }
        public decimal Construction { get; set; }
        public bool UsedHospital { get; set; }
        public int PlayerTypeID { get; set; }
        public bool Worked { get; set; }
        public int DayWorkedRow { get; set; }
        public bool HasEaten { get; set; }
        public decimal Selling { get; set; }
        public bool Trained { get; set; }
        public int DamageTaken { get; set; }
        public int HardWorkerMedals { get; set; }
        public int SuperSoldierMedals { get; set; }
        public int SuperJournalistMedals { get; set; }
        public int CongressMedals { get; set; }
        public int PresidentMedals { get; set; }
        public int BattleHeroMedals { get; set; }
        public int WarHeroMedals { get; set; }
        public int RessistanceHeroMedals { get; set; }
        public int SoldArticles { get; set; }
        public int DrankTeas { get; set; }
        public int ExperienceLevel { get; set; }
        public int LastActivityDay { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual PlayerType PlayerType { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual Entity Entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractJobOffer> ContractJobOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobContract> JobContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongressVoting> CongressVotings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyPresidentVote> PartyPresidentVotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Party> Parties { get; set; }
        public virtual PartyMember PartyMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyJoinRequest> PartyJoinRequests { get; set; }
        public virtual CompanyEmployee CompanyEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyPresidentCandidate> PartyPresidentCandidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongressVotingComment> CongressVotingComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongressCandidateVote> CongressCandidateVotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongressCandidate> CongressCandidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country> CountriesPresident { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresidentCandidate> PresidentCandidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresidentVote> PresidentVotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organisation> Organisations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BattleParticipant> BattleParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewspaperJournalist> NewspaperJournalists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BugReport> BugReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friend> Friends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friend> Friends1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FriendRequest> FriendRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FriendRequest> FriendRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyInvite> PartyInvites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<War> Wars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevIssueComment> DevIssueComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevIssue> DevIssues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevIssueVote> DevIssueVotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Upload> Uploads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongressVote> CongressVotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Congressman> Congressmen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelRoom> HotelRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelManager> HotelManagers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<House> Houses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyMemberEvent> PartyMemberEvents { get; set; }
    }
}
