//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.JobOffers = new HashSet<JobOffer>();
            this.CompanyEmployees = new HashSet<CompanyEmployee>();
            this.MarketOffers = new HashSet<MarketOffer>();
            this.CompanyManagers = new HashSet<CompanyManager>();
            this.CompanyFinanceSummaries = new HashSet<CompanyFinanceSummary>();
        }
    
        public int ID { get; set; }
        public int RegionID { get; set; }
        public int ProductID { get; set; }
        public int Quality { get; set; }
        public decimal Queue { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public int WorkTypeID { get; set; }
        public int DefaultMinHP { get; set; }
        public int CompanyTypeID { get; set; }
        public bool InformedAboutNotEnoughSalaryToday { get; set; }
        public bool InformedAboutNotEnoughRawToday { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Entity Owner { get; set; }
        public virtual Product Product { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOffer> JobOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyEmployee> CompanyEmployees { get; set; }
        public virtual CompanyType CompanyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketOffer> MarketOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyManager> CompanyManagers { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual Construction Construction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFinanceSummary> CompanyFinanceSummaries { get; set; }
    }
}
