//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyFinanceSummary
    {
        public int CompanyID { get; set; }
        public int Day { get; set; }
        public int CurrencyID { get; set; }
        public decimal SellRevenue { get; set; }
        public decimal GiftBalance { get; set; }
        public decimal TradeBalance { get; set; }
        public decimal SalaryCost { get; set; }
        public decimal ImportTax { get; set; }
        public decimal ExportTax { get; set; }
        public decimal Vat { get; set; }
        public decimal JobOfferCost { get; set; }
        public decimal MarketOfferCost { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
