//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyEmployee
    {
        public int CitizenID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> JobContractID { get; set; }
        public Nullable<decimal> TodayProduction { get; set; }
        public decimal Salary { get; set; }
        public int MinHP { get; set; }
        public Nullable<int> TodayHP { get; set; }
        public Nullable<decimal> TodaySalary { get; set; }
        public int StartDay { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Company Company { get; set; }
        public virtual JobContract JobContract { get; set; }
    }
}
