//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyManager
    {
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public int EntityID { get; set; }
        public bool PostJobOffers { get; set; }
        public bool PostMarketOffers { get; set; }
        public bool ManageWorkers { get; set; }
        public bool Switch { get; set; }
        public bool ChangeAvatar { get; set; }
        public bool ManageManagers { get; set; }
        public bool SeeWallet { get; set; }
        public bool ManageEquipment { get; set; }
        public bool UpgradeCompany { get; set; }
        public int Priority { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
