//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongressCandidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongressCandidate()
        {
            this.CongressCandidateVotes = new HashSet<CongressCandidateVote>();
        }
    
        public int ID { get; set; }
        public int CandidateID { get; set; }
        public int RegionID { get; set; }
        public int CongressCandidateVotingID { get; set; }
        public int CongressCandidateStatusID { get; set; }
        public int PartyID { get; set; }
    
        public virtual CongressCandidateVoting CongressCandidateVoting { get; set; }
        public virtual Region Region { get; set; }
        public virtual CongressCandidateStatus CongressCandidateStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongressCandidateVote> CongressCandidateVotes { get; set; }
        public virtual Citizen Citizen { get; set; }
        public virtual Party Party { get; set; }
    }
}
