//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongressCandidateVoting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongressCandidateVoting()
        {
            this.CongressCandidates = new HashSet<CongressCandidate>();
            this.CongressCandidateVotes = new HashSet<CongressCandidateVote>();
        }
    
        public int ID { get; set; }
        public int CountryID { get; set; }
        public int VotingDay { get; set; }
        public int VotingStatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongressCandidate> CongressCandidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongressCandidateVote> CongressCandidateVotes { get; set; }
        public virtual Country Country { get; set; }
        public virtual VotingStatus VotingStatus { get; set; }
    }
}
