//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongressVote
    {
        public int CongressVotingID { get; set; }
        public int CitizenID { get; set; }
        public int VoteTypeID { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual CongressVoting CongressVoting { get; set; }
        public virtual VotingType VotingType { get; set; }
        public virtual VoteType VoteType { get; set; }
    }
}
