//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongressVotingReservedMoney
    {
        public int ID { get; set; }
        public int CongressVotingID { get; set; }
        public int CurrencyID { get; set; }
        public decimal Amount { get; set; }
    
        public virtual CongressVoting CongressVoting { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
