//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongressCandidateVote
    {
        public int CongressCandidateVotingID { get; set; }
        public int CitizenID { get; set; }
        public int SelectedCandidateID { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual CongressCandidateVoting CongressCandidateVoting { get; set; }
        public virtual CongressCandidate CongressCandidate { get; set; }
    }
}
