//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractJobOffer
    {
        public int ID { get; set; }
        public decimal MinSalary { get; set; }
        public int MinHP { get; set; }
        public int Length { get; set; }
        public int SigneeID { get; set; }
    
        public virtual JobOffer JobOffer { get; set; }
        public virtual Citizen Citizen { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
