//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryInWar
    {
        public int CountryID { get; set; }
        public int WarID { get; set; }
        public bool IsAttacker { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual War War { get; set; }
    }
}
