//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.Regions = new HashSet<Region>();
            this.Citizens = new HashSet<Citizen>();
            this.CongressVotings = new HashSet<CongressVoting>();
            this.Parties = new HashSet<Party>();
            this.CongressCandidateVotings = new HashSet<CongressCandidateVoting>();
            this.PresidentVotings = new HashSet<PresidentVoting>();
            this.Organisations = new HashSet<Organisation>();
            this.MarketOffers = new HashSet<MarketOffer>();
            this.CountryInWars = new HashSet<CountryInWar>();
            this.MPPsFirstCountry = new HashSet<MilitaryProtectionPact>();
            this.MPPsSecondCountry = new HashSet<MilitaryProtectionPact>();
            this.Truces = new HashSet<Truce>();
            this.Truces1 = new HashSet<Truce>();
            this.AttackerWars = new HashSet<War>();
            this.DefenderWars = new HashSet<War>();
            this.JobOffers = new HashSet<JobOffer>();
            this.Newspapers = new HashSet<Newspaper>();
            this.CreatedEmbargoes = new HashSet<Embargo>();
            this.Embargoes = new HashSet<Embargo>();
            this.ProductTaxes = new HashSet<ProductTax>();
            this.CoreRegions = new HashSet<Region>();
            this.MPPOffersFirstCountry = new HashSet<MilitaryProtectionPactOffer>();
            this.MPPOffersSecondCountry = new HashSet<MilitaryProtectionPactOffer>();
            this.HospitalNationalityHealingOptions = new HashSet<HospitalNationalityHealingOption>();
            this.Congressmen = new HashSet<Congressman>();
            this.CountryEvents = new HashSet<CountryEvent>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CapitalID { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<int> PresidentID { get; set; }
        public string Color { get; set; }
        public string GreetingMessage { get; set; }
        public Nullable<int> NationalShoutboxChannelID { get; set; }
        public Nullable<int> NationalTradeShoutboxChannelID { get; set; }
        public Nullable<int> NationalHelpShoutboxChannelID { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Region Capital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Region> Regions { get; set; }
        public virtual CountryPolicy CountryPolicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citizen> Citizens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongressVoting> CongressVotings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Party> Parties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongressCandidateVoting> CongressCandidateVotings { get; set; }
        public virtual Citizen President { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresidentVoting> PresidentVotings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organisation> Organisations { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketOffer> MarketOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountryInWar> CountryInWars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MilitaryProtectionPact> MPPsFirstCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MilitaryProtectionPact> MPPsSecondCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Truce> Truces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Truce> Truces1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<War> AttackerWars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<War> DefenderWars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOffer> JobOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Newspaper> Newspapers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Embargo> CreatedEmbargoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Embargo> Embargoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTax> ProductTaxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Region> CoreRegions { get; set; }
        public virtual ShoutboxChannel NationalShoutboxChannel { get; set; }
        public virtual ShoutboxChannel NationalHelpShoutboxChannel { get; set; }
        public virtual ShoutboxChannel NationalTradeShoutboxChannel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MilitaryProtectionPactOffer> MPPOffersFirstCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MilitaryProtectionPactOffer> MPPOffersSecondCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalNationalityHealingOption> HospitalNationalityHealingOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Congressman> Congressmen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountryEvent> CountryEvents { get; set; }
    }
}
