//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevIssueUploadedFile
    {
        public long ID { get; set; }
        public int DevIssueID { get; set; }
        public string Filename { get; set; }
        public string OriginalFilename { get; set; }
    
        public virtual DevIssue DevIssue { get; set; }
    }
}
