//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Embargo
    {
        public int ID { get; set; }
        public int StartDay { get; set; }
        public Nullable<int> EndDay { get; set; }
        public bool Active { get; set; }
        public int CreatorCountryID { get; set; }
        public int EmbargoedCountryID { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual Country CreatorCountry { get; set; }
        public virtual Country EmbargoedCountry { get; set; }
    }
}
