//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SociatisEntities : DbContext
    {
        public SociatisEntities()
            : base("name=SociatisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<VerificationEmail> VerificationEmails { get; set; }
        public virtual DbSet<Wallet> Wallets { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<EntityType> EntityTypes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<CountryPolicy> CountryPolicies { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<PlayerType> PlayerTypes { get; set; }
        public virtual DbSet<TransactionLog> TransactionLogs { get; set; }
        public virtual DbSet<ContractJobOffer> ContractJobOffers { get; set; }
        public virtual DbSet<JobOffer> JobOffers { get; set; }
        public virtual DbSet<JobType> JobTypes { get; set; }
        public virtual DbSet<NormalJobOffer> NormalJobOffers { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<ConfigurationTable> ConfigurationTables { get; set; }
        public virtual DbSet<EquipmentItem> EquipmentItems { get; set; }
        public virtual DbSet<Citizen> Citizens { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<MessageThread> MessageThreads { get; set; }
        public virtual DbSet<WalletMoney> WalletMoneys { get; set; }
        public virtual DbSet<JobContract> JobContracts { get; set; }
        public virtual DbSet<CommentRestriction> CommentRestrictions { get; set; }
        public virtual DbSet<CongressVoting> CongressVotings { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<PartyPresidentVote> PartyPresidentVotes { get; set; }
        public virtual DbSet<PartyPresidentVoting> PartyPresidentVotings { get; set; }
        public virtual DbSet<PartyRole> PartyRoles { get; set; }
        public virtual DbSet<VoteType> VoteTypes { get; set; }
        public virtual DbSet<VotingStatus> VotingStatuses { get; set; }
        public virtual DbSet<VotingType> VotingTypes { get; set; }
        public virtual DbSet<JoinMethod> JoinMethods { get; set; }
        public virtual DbSet<PartyMember> PartyMembers { get; set; }
        public virtual DbSet<PartyJoinRequest> PartyJoinRequests { get; set; }
        public virtual DbSet<CompanyEmployee> CompanyEmployees { get; set; }
        public virtual DbSet<PartyPresidentCandidate> PartyPresidentCandidates { get; set; }
        public virtual DbSet<CongressVotingComment> CongressVotingComments { get; set; }
        public virtual DbSet<CongressCandidate> CongressCandidates { get; set; }
        public virtual DbSet<CongressCandidateVote> CongressCandidateVotes { get; set; }
        public virtual DbSet<CongressCandidateVoting> CongressCandidateVotings { get; set; }
        public virtual DbSet<CongressCandidateStatus> CongressCandidateStatuses { get; set; }
        public virtual DbSet<PresidentCandidate> PresidentCandidates { get; set; }
        public virtual DbSet<PresidentCandidateStatus> PresidentCandidateStatuses { get; set; }
        public virtual DbSet<PresidentVoting> PresidentVotings { get; set; }
        public virtual DbSet<PresidentVote> PresidentVotes { get; set; }
        public virtual DbSet<Passage> Passages { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<ResourceType> ResourceTypes { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<MarketOffer> MarketOffers { get; set; }
        public virtual DbSet<ProductTaxType> ProductTaxTypes { get; set; }
        public virtual DbSet<Warning> Warnings { get; set; }
        public virtual DbSet<BattleParticipant> BattleParticipants { get; set; }
        public virtual DbSet<Battle> Battles { get; set; }
        public virtual DbSet<CountryInWar> CountryInWars { get; set; }
        public virtual DbSet<MilitaryProtectionPact> MilitaryProtectionPacts { get; set; }
        public virtual DbSet<Truce> Truces { get; set; }
        public virtual DbSet<War> Wars { get; set; }
        public virtual DbSet<Embargo> Embargoes { get; set; }
        public virtual DbSet<ArticleComment> ArticleComments { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Newspaper> Newspapers { get; set; }
        public virtual DbSet<NewspaperJournalist> NewspaperJournalists { get; set; }
        public virtual DbSet<ArticleVote> ArticleVotes { get; set; }
        public virtual DbSet<BugReport> BugReports { get; set; }
        public virtual DbSet<MailboxMessage> MailboxMessages { get; set; }
        public virtual DbSet<ProductTax> ProductTaxes { get; set; }
        public virtual DbSet<DebugDayChanx> DebugDayChanges { get; set; }
        public virtual DbSet<MonetaryOffer> MonetaryOffers { get; set; }
        public virtual DbSet<MonetaryOfferType> MonetaryOfferTypes { get; set; }
        public virtual DbSet<MonetaryTransaction> MonetaryTransactions { get; set; }
        public virtual DbSet<Friend> Friends { get; set; }
        public virtual DbSet<FriendRequest> FriendRequests { get; set; }
        public virtual DbSet<Polygon> Polygons { get; set; }
        public virtual DbSet<PolygonPoint> PolygonPoints { get; set; }
        public virtual DbSet<PartyInvite> PartyInvites { get; set; }
        public virtual DbSet<CongressVotingRejectionReason> CongressVotingRejectionReasons { get; set; }
        public virtual DbSet<LawAllowHolder> LawAllowHolders { get; set; }
        public virtual DbSet<ReservedEntityName> ReservedEntityNames { get; set; }
        public virtual DbSet<CongressVotingReservedMoney> CongressVotingReservedMoneys { get; set; }
        public virtual DbSet<CompanyManager> CompanyManagers { get; set; }
        public virtual DbSet<VotingGreetingMessage> VotingGreetingMessages { get; set; }
        public virtual DbSet<ShoutboxChannel> ShoutboxChannels { get; set; }
        public virtual DbSet<ShoutboxMessage> ShoutboxMessages { get; set; }
        public virtual DbSet<GiftTransaction> GiftTransactions { get; set; }
        public virtual DbSet<Trade> Trades { get; set; }
        public virtual DbSet<TradeMoney> TradeMoneys { get; set; }
        public virtual DbSet<TradeProduct> TradeProducts { get; set; }
        public virtual DbSet<TradeStatus> TradeStatuses { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<MilitaryProtectionPactOffer> MilitaryProtectionPactOffers { get; set; }
        public virtual DbSet<DevIssueComment> DevIssueComments { get; set; }
        public virtual DbSet<DevIssueLabelType> DevIssueLabelTypes { get; set; }
        public virtual DbSet<DevIssue> DevIssues { get; set; }
        public virtual DbSet<VisibilityOption> VisibilityOptions { get; set; }
        public virtual DbSet<DevIssueUploadedFile> DevIssueUploadedFiles { get; set; }
        public virtual DbSet<DevIssueVote> DevIssueVotes { get; set; }
        public virtual DbSet<UploadLocation> UploadLocations { get; set; }
        public virtual DbSet<Upload> Uploads { get; set; }
        public virtual DbSet<AllowedEmail> AllowedEmails { get; set; }
        public virtual DbSet<CongressVote> CongressVotes { get; set; }
        public virtual DbSet<NewDay> NewDays { get; set; }
        public virtual DbSet<HospitalNationalityHealingOption> HospitalNationalityHealingOptions { get; set; }
        public virtual DbSet<Congressman> Congressmen { get; set; }
        public virtual DbSet<Construction> Constructions1 { get; set; }
        public virtual DbSet<HotelPrice> HotelPrices { get; set; }
        public virtual DbSet<HotelRoom> HotelRooms { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<HotelManager> HotelManagers { get; set; }
        public virtual DbSet<FurnitureType> FurnitureTypes { get; set; }
        public virtual DbSet<HouseChest> HouseChests { get; set; }
        public virtual DbSet<House> Houses { get; set; }
        public virtual DbSet<HouseFurniture> HouseFurnitures { get; set; }
        public virtual DbSet<HouseChestItem> HouseChestItems { get; set; }
        public virtual DbSet<SellHouse> SellHouses { get; set; }
        public virtual DbSet<CompanyFinanceSummary> CompanyFinanceSummaries { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<CountryEvent> CountryEvents { get; set; }
        public virtual DbSet<CountryEventType> CountryEventTypes { get; set; }
        public virtual DbSet<CountryVotingEvent> CountryVotingEvents { get; set; }
        public virtual DbSet<BattleEvent> BattleEvents { get; set; }
        public virtual DbSet<PartyMemberEvent> PartyMemberEvents { get; set; }
        public virtual DbSet<BattleStatus> BattleStatuses { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<MemberStatus> MemberStatuses { get; set; }
        public virtual DbSet<PartyEventType> PartyEventTypes { get; set; }
        public virtual DbSet<AggregatedCounter> AggregatedCounters { get; set; }
        public virtual DbSet<Counter> Counters { get; set; }
        public virtual DbSet<Hash> Hashes { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobParameter> JobParameters { get; set; }
        public virtual DbSet<JobQueue> JobQueues { get; set; }
        public virtual DbSet<List> Lists { get; set; }
        public virtual DbSet<Schema> Schemata { get; set; }
        public virtual DbSet<Server> Servers { get; set; }
        public virtual DbSet<Set> Sets { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<PartyEvent> PartyEvents { get; set; }
        public virtual DbSet<WarEvent> WarEvents { get; set; }
        public virtual DbSet<WarStatus> WarStatuses { get; set; }
    }
}
