//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int ID { get; set; }
        public int ProposerCitizenID { get; set; }
        public int SecondCitizenID { get; set; }
        public int DayCreated { get; set; }
    
        public virtual Citizen ProposerCitizen { get; set; }
        public virtual Citizen SecondCitizen { get; set; }
    }
}
