//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftTransaction
    {
        public int ID { get; set; }
        public int SourceEntityID { get; set; }
        public int DestinationEntityID { get; set; }
        public int ProductID { get; set; }
        public int Amount { get; set; }
        public int Quality { get; set; }
        public int Day { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> FuelUsed { get; set; }
    
        public virtual Entity Destination { get; set; }
        public virtual Entity Source { get; set; }
        public virtual Product Product { get; set; }
    }
}
