//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalNationalityHealingOption
    {
        public int HospitalID { get; set; }
        public int CountryID { get; set; }
        public Nullable<decimal> HealingPrice { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Hospital Hospital { get; set; }
    }
}
