//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelManager
    {
        public int HotelID { get; set; }
        public int CitizenID { get; set; }
        public bool CanBuildRooms { get; set; }
        public bool CanMakeDeliveries { get; set; }
        public bool CanUseWallet { get; set; }
        public bool CanSetPrices { get; set; }
        public bool CanSwitchInto { get; set; }
        public bool CanManageManagers { get; set; }
        public int Priority { get; set; }
        public bool CanManageEquipment { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
