//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelPrice
    {
        public int HotelID { get; set; }
        public Nullable<decimal> PriceQ1 { get; set; }
        public Nullable<decimal> PriceQ2 { get; set; }
        public Nullable<decimal> PriceQ3 { get; set; }
        public Nullable<decimal> PriceQ4 { get; set; }
        public Nullable<decimal> PriceQ5 { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
