//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.HotelRooms = new HashSet<HotelRoom>();
            this.HotelManagers = new HashSet<HotelManager>();
        }
    
        public int ID { get; set; }
        public decimal Condition { get; set; }
        public int OwnerID { get; set; }
        public int RegionID { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual HotelPrice HotelPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelRoom> HotelRooms { get; set; }
        public virtual Entity Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelManager> HotelManagers { get; set; }
        public virtual Region Region { get; set; }
    }
}
