//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRoom
    {
        public long ID { get; set; }
        public int HotelID { get; set; }
        public int Quality { get; set; }
        public Nullable<int> InhabitantID { get; set; }
        public Nullable<int> StayingFromDay { get; set; }
        public Nullable<int> StayingToDay { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Citizen Inhabitant { get; set; }
    }
}
