//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseFurniture
    {
        public long ID { get; set; }
        public long HouseID { get; set; }
        public int FurnitureTypeID { get; set; }
        public int Quality { get; set; }
    
        public virtual FurnitureType FurnitureType { get; set; }
        public virtual House House { get; set; }
        public virtual HouseChest HouseChest { get; set; }
    }
}
