//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOffer
    {
        public int ID { get; set; }
        public int TypeID { get; set; }
        public int CompanyID { get; set; }
        public int Amount { get; set; }
        public decimal MinSkill { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ContractJobOffer ContractJobOffer { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual NormalJobOffer NormalJobOffer { get; set; }
        public virtual Country Country { get; set; }
    }
}
