//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailboxMessage
    {
        public int Viewers_EntityID { get; set; }
        public int MessageThreads1_ID { get; set; }
        public bool Unread { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual MessageThread MessageThread { get; set; }
    }
}
