//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public int ThreadID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public int Day { get; set; }
    
        public virtual Entity Author { get; set; }
        public virtual MessageThread MessageThread { get; set; }
    }
}
