//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilitaryProtectionPact
    {
        public int ID { get; set; }
        public int StartDay { get; set; }
        public int EndDay { get; set; }
        public int FirstCountryID { get; set; }
        public int SecondCountryID { get; set; }
        public bool Active { get; set; }
    
        public virtual Country FirstCountry { get; set; }
        public virtual Country SecondCountry { get; set; }
    }
}
