//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonetaryTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonetaryTransaction()
        {
            this.MonetaryOffers = new HashSet<MonetaryOffer>();
        }
    
        public int ID { get; set; }
        public int SellerCurrencyID { get; set; }
        public int BuyerCurrencyID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<int> SellerID { get; set; }
        public int Day { get; set; }
        public System.DateTime Date { get; set; }
        public int Amount { get; set; }
        public decimal Rate { get; set; }
        public decimal BuyerTax { get; set; }
        public decimal SellerTax { get; set; }
    
        public virtual Currency BuyerCurrency { get; set; }
        public virtual Currency SellerCurrency { get; set; }
        public virtual Entity Buyer { get; set; }
        public virtual Entity Seller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonetaryOffer> MonetaryOffers { get; set; }
    }
}
