//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonetaryOffer
    {
        public int ID { get; set; }
        public int SellCurrencyID { get; set; }
        public int BuyCurrencyID { get; set; }
        public int SellerID { get; set; }
        public int Amount { get; set; }
        public decimal Rate { get; set; }
        public int OfferTypeID { get; set; }
        public int AmountSold { get; set; }
        public decimal Tax { get; set; }
        public decimal MinimumTax { get; set; }
        public decimal TaxReservedMoney { get; set; }
        public decimal OfferReservedMoney { get; set; }
        public decimal ValueOfSold { get; set; }
        public Nullable<int> LastTransactionID { get; set; }
    
        public virtual Currency BuyCurrency { get; set; }
        public virtual Currency SellCurrency { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual MonetaryOfferType MonetaryOfferType { get; set; }
        public virtual MonetaryTransaction LastTransaction { get; set; }
    }
}
