//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyEvent
    {
        public long EventID { get; set; }
        public int PartyID { get; set; }
        public int PartyEventTypeID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Party Party { get; set; }
        public virtual PartyMemberEvent PartyMemberEvent { get; set; }
    }
}
