//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyMemberEvent
    {
        public long EventID { get; set; }
        public int MemberStatusID { get; set; }
        public int CitizenID { get; set; }
        public int InitiatorID { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Entity Initiator { get; set; }
        public virtual MemberStatus MemberStatus { get; set; }
        public virtual PartyEvent PartyEvent { get; set; }
    }
}
