//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyPresidentVote
    {
        public int PartyPresidentVotingID { get; set; }
        public int CitizenID { get; set; }
        public int PartyPresidentCandidateID { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual PartyPresidentVoting PartyPresidentVoting { get; set; }
        public virtual PartyPresidentCandidate PartyPresidentCandidate { get; set; }
    }
}
