//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyPresidentVoting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartyPresidentVoting()
        {
            this.PartyPresidentVotes = new HashSet<PartyPresidentVote>();
            this.PartyPresidentCandidates = new HashSet<PartyPresidentCandidate>();
        }
    
        public int ID { get; set; }
        public int PartyID { get; set; }
        public int VotingStatusID { get; set; }
        public int VotingDay { get; set; }
    
        public virtual Party Party { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyPresidentVote> PartyPresidentVotes { get; set; }
        public virtual VotingStatus VotingStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyPresidentCandidate> PartyPresidentCandidates { get; set; }
    }
}
