//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Party()
        {
            this.PartyPresidentVotings = new HashSet<PartyPresidentVoting>();
            this.PartyMembers = new HashSet<PartyMember>();
            this.PartyJoinRequests = new HashSet<PartyJoinRequest>();
            this.CongressCandidates = new HashSet<CongressCandidate>();
            this.PartyInvites = new HashSet<PartyInvite>();
            this.PartyEvents = new HashSet<PartyEvent>();
        }
    
        public int ID { get; set; }
        public int FoundationDay { get; set; }
        public int FoundatorID { get; set; }
        public int JoinMethodID { get; set; }
        public int CountryID { get; set; }
    
        public virtual Entity Entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyPresidentVoting> PartyPresidentVotings { get; set; }
        public virtual Citizen Foundator { get; set; }
        public virtual JoinMethod JoinMethod { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyMember> PartyMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyJoinRequest> PartyJoinRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongressCandidate> CongressCandidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyInvite> PartyInvites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyEvent> PartyEvents { get; set; }
    }
}
