//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyInvite
    {
        public int ID { get; set; }
        public int PartyID { get; set; }
        public int CitizenID { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Party Party { get; set; }
    }
}
