//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passage
    {
        public int ID { get; set; }
        public int FirstRegionID { get; set; }
        public int SecondRegionID { get; set; }
        public int Distance { get; set; }
    
        public virtual Region FirstRegion { get; set; }
        public virtual Region SecondRegion { get; set; }
    }
}
