//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresidentCandidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PresidentCandidate()
        {
            this.PresidentVotes = new HashSet<PresidentVote>();
        }
    
        public int ID { get; set; }
        public int CandidateID { get; set; }
        public int CandidateStatusID { get; set; }
        public int VotingID { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual PresidentCandidateStatus PresidentCandidateStatus { get; set; }
        public virtual PresidentVoting PresidentVoting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresidentVote> PresidentVotes { get; set; }
    }
}
