//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresidentVote
    {
        public int ID { get; set; }
        public int PresidentVotingID { get; set; }
        public int CitizenID { get; set; }
        public int CandidateID { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual PresidentCandidate PresidentCandidate { get; set; }
        public virtual PresidentVoting PresidentVoting { get; set; }
    }
}
