//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresidentVoting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PresidentVoting()
        {
            this.PresidentCandidates = new HashSet<PresidentCandidate>();
            this.PresidentVotes = new HashSet<PresidentVote>();
        }
    
        public int ID { get; set; }
        public int CountryID { get; set; }
        public int StartDay { get; set; }
        public int VotingStatusID { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresidentCandidate> PresidentCandidates { get; set; }
        public virtual VotingStatus VotingStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresidentVote> PresidentVotes { get; set; }
    }
}
