//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTax
    {
        public int CountryID { get; set; }
        public int ProductID { get; set; }
        public int ForeignCountryID { get; set; }
        public decimal TaxRate { get; set; }
        public int ProductTaxTypeID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductTaxType ProductTaxType { get; set; }
    }
}
