//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoutboxMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoutboxMessage()
        {
            this.Children = new HashSet<ShoutboxMessage>();
        }
    
        public long ID { get; set; }
        public int AuthorID { get; set; }
        public int ChannelID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string Message { get; set; }
        public System.DateTime Time { get; set; }
        public int Day { get; set; }
    
        public virtual Entity Author { get; set; }
        public virtual ShoutboxChannel ShoutboxChannel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoutboxMessage> Children { get; set; }
        public virtual ShoutboxMessage Parent { get; set; }
    }
}
