//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trade()
        {
            this.TradeMoneys = new HashSet<TradeMoney>();
            this.TradeProducts = new HashSet<TradeProduct>();
        }
    
        public long ID { get; set; }
        public Nullable<int> SourceEntityID { get; set; }
        public Nullable<int> DestinationEntityID { get; set; }
        public int Day { get; set; }
        public System.DateTime DateTime { get; set; }
        public int TradeStatusID { get; set; }
        public bool SourceAccepted { get; set; }
        public bool DestinationAccepted { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> SourceUsedFuelAmount { get; set; }
        public Nullable<int> DestinationUsedFuelAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradeMoney> TradeMoneys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradeProduct> TradeProducts { get; set; }
        public virtual TradeStatus TradeStatus { get; set; }
        public virtual Entity Destination { get; set; }
        public virtual Entity Source { get; set; }
    }
}
