//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warning
    {
        public int ID { get; set; }
        public int EntityID { get; set; }
        public string Message { get; set; }
        public bool Unread { get; set; }
        public int Day { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Entity Entity { get; set; }
    }
}
